config/routes.rb
Ilie::Application.routes.draw do
  
  root to: 'static_pages#home'
  
 match '/about', to: 'static_pages#about'
 
 match '/program/sat', to: 'static_pages#program_sat'
 
 match '/program/ssat', to: 'static_pages#program_ssat'
 
 match '/program/toefl', to: 'static_pages#program_toefl'
 
 match '/program/consulting', to: 'static_pages#program_consulting'
 
match '/contact', to: 'static_pages#contact'

match '/schedule', to: 'static_pages#schedule'

match '/employment', to: 'static_pages#employment'

match '/location', to: 'static_pages#location'

match '/news', to: 'news_pages#news'

match '/studyinfo', to: 'news_pages#studyinfo'

match '/faq', to: 'news_pages#faq'

match '/news', to: 'news_pages#news'

match '/topuniv', to: 'news_pages#topuniv'

match '/resources', to: 'news_pages#resources'
 
match '/teachers', to: 'news_pages#teachers'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/news_pages_controller.rb
class NewsPagesController < ApplicationController

  def program
  end

  def teachers
  end
  
  def studyinfo
  end
  
  def topuniv
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def resources
  end

  def contact
  end

  def schedule
  end
  
  def location
  end
  
  def program_sat
  end
  
  def program_ssat
  end
  
  def program_toefl
  end
  
  def program_consulting
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
		content_for(:title) {page_title}
	end
end

app/helpers/news_pages_helper.rb
module NewsPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
	&copy; 2010 QwestPrep International
	<nav class="nav nav-pills pull-right">
			<li><%= link_to "联系我们/Contact Us", contact_path %></li>
			<li><%= link_to "求职招聘/Employment", employment_path %></li>
			<li><%= link_to "Get Started", "#" %></li>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
	<div class="navbar">
		<nav id="nav_left">
          <%= link_to image_tag('/logo_web2.png'), root_path, :id => "logo" %>
		</nav>
		<p class="emphasis" style="float:right;">电话: 02152125489</p>
		
		<ul id="nav_right" style="clear:right;">
				<button class="btn btn-large" type="button"><%= link_to "关于我们", about_path %></button>
				<span class="dropdown">
				<a class="btn btn-large dropdown dropdown-toggle" data-toggle="dropdown" href="#">  课程安排  </a>
					<ul class="dropdown-menu">
						<%= link_to "SAT 课程", program_sat_path %>	
						<%= link_to "SSAT 课程", program_ssat_path %>
						<%= link_to "TOEFL 课程", program_toefl_path %>
						<%= link_to "留学咨询", program_consulting_path %>
					</ul>
				</span>
				<button class="btn btn-large" type="button"><%= link_to "联系我们", contact_path %></button>
				<button class="btn btn-large" type="button"><%= link_to "信息", news_path %></button>
			</div>
		</ul>
	</div>
</div>	

app/views/layouts/_nav.html.erb
<div class="container">
	<ul class="nav nav-pills">
		<li class="active">
			<%= link_to "About Us", about_path %>
		</li>
		<li class="active">
			<%= link_to "Why Study Abroad?", studyinfo_path %>
		</li>
		<li class="active">
			<%= link_to "Our Teachers", teachers_path %>
		</li>
		<li class="active">
			<%= link_to "Top Universities", topuniv_path %>
		</li>
		<li class="active">
			<%= link_to "SAT Resources", resources_path %>
		</li>
		<li class="active">
			<%= link_to "Upcoming Classes", schedule_path %>
		</li>
		<li class="active">
			<%= link_to "Contact Us", contact_path %>
		</li>
		<li class="active">
			<%= link_to "FAQ", faq_path %>
		</li>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>留西 QwestPrep - <%= yield :title %></title>
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<%= favicon_link_tag %>
	<%= stylesheet_link_tag    "application", :media => "all" %>

	<%= csrf_meta_tags %>
	
	<meta name="google-site-verification" content="1-qPhsG5ZAgLkUFiT6_gNkanuHDgDMqsOO019z5D6l4" />

	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-35990945-1']);
		_gaq.push(['_trackPageview']);
		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
	</script>
</head>
<body>
	<div class="container-fluid">
		<%= render 'layouts/header' %>
			<!-- <%= render 'layouts/nav' %> -->
	    <% flash.each do |key, value| %>
			<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>

<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="../assets/js/jquery.js"></script>
<script src="../assets/js/bootstrap-transition.js"></script>
<script src="../assets/js/bootstrap-alert.js"></script>
<script src="../assets/js/bootstrap-modal.js"></script>
<script src="../assets/js/bootstrap-dropdown.js"></script>
<script src="../assets/js/bootstrap-scrollspy.js"></script>
<script src="../assets/js/bootstrap-tab.js"></script>
<script src="../assets/js/bootstrap-tooltip.js"></script>
<script src="../assets/js/bootstrap-popover.js"></script>
<script src="../assets/js/bootstrap-button.js"></script>
<script src="../assets/js/bootstrap-collapse.js"></script>
<script src="../assets/js/bootstrap-carousel.js"></script>
<script src="../assets/js/bootstrap-typeahead.js"></script>

</html>

app/views/news_pages/faq.html.erb
<h1>This is the FAQ, Son</h1>
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Collapsible Group Item #1
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse in">
      <div class="accordion-inner">
        Anim pariatur cliche...
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
        Collapsible Group Item #2
      </a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
      <div class="accordion-inner">
        Anim pariatur cliche...
      </div>
    </div>
  </div>
</div>

app/views/news_pages/news.html.erb
<div class="container">
	<div class="row">
		<h1>我们的信息</h1>
	</div>
	<div class="row">
		<div class="span4">
			<ul>
			<li><%= link_to "信息", news_path %></li>
			<li><%= link_to "美国大学", topuniv_path %></li>
			<li><%= link_to "FAQ", faq_path %></li>
			<li><%= link_to "为什么留学", studyinfo_path %></li>
			<li><%= link_to "SAT是什么", resources_path %></li>
			<li><%= link_to "我们的老师", teachers_path %></li>
			</ul>
		</div>
		</div class="span9">
		</div>
	</div>

app/views/news_pages/resources.html.erb
<div class="row">
		<h1>Test Preparation Resources</h1>
			<p class="lead">There are plenty of SAT prep resources available online to help you get started. </p>
			<p>While no substitute for the personalized attention of a professional instructor, these
				resources can help you develop a test preparation plan and do some basic diagnostics work.
			<p>Once you're done looking through the resources featured on this page, please don't hesistate to contact one
				of our professional course consultants at 021-5212-5489 or at <a href="mailto:information@qwestprep.com">information@qwestprep.com</a> in order to arrange a graded mock exam and personalized study
				plan consultation, free of charge.</p>
</div>
<div class="row">		
		<ul>
			<li><a href="http://www.collegeboard.org">Collegeboard.org</a></li>
			<li><a href="https://bigfuture.collegeboard.org/college-search">College Search</a></li>
			<li><a href="http://sat.collegeboard.org/register">SAT Registration</a></p></li>
			<li><a href="http://sat.collegeboard.org/practice/sat-question-of-the-day">The Official SAT Question of the Day</a></li>
			<li><a href="https://bigfuture.collegeboard.org/scholarship-search">Scholarship Search</a></li>
			<li><a href="https://bigfuture.collegeboard.org/majors-careers">Major and Career Profiles</a></li>
			<li><a href="http://sat.collegeboard.org/practice/sat-practice-test">Free Official SAT Practice Test</a></li>
			<li><a href="http://img.sparknotes.com/content/testprep/pdf/sat.vocab.pdf">1000 High Frequency SAT Vocab Words</a></li>
		</ul>
	</div>
</div>

app/views/news_pages/studyinfo.html.erb
<h1>Why Study Abroad?</h1>

app/views/news_pages/teachers.html.erb
<h1>StaticPages#teachers</h1>
<p>Find me in app/views/static_pages/teachers.html.erb</p>

app/views/news_pages/topuniv.html.erb
<div class="container">
	<div class="row">
		<h1 class="center">美国排名前50的大学</h1>
	</div>
	<div class="row">
		
<style type="text/css">
table.tableizer-table {
	text-align: left;
	width: 100%;
	font-size: 100%;
	padding: 5px;
	font-family: Arial, Helvetica, sans-serif;
} 
.tableizer-table td {
	padding: 8px;
	font-size:0.875em;
	margin: 3px;
	border-bottom: 1px solid #ccc;
}

.tableizer-table td:hover {
	
}

.tableizer-table th {
	font-size: 1.0em;
	padding: 5px; 
	color: #000000;
	font-weight: bold;
	border-bottom: 2px solid #fff
}
</style>

<table class="tableizer-table">
<tr class="tableizer-firstrow"><th>排名</th><th>大学</th><th>录取率</th><th>录取总分</th><th>批判性阅读</th><th>数学</th></tr>
 <tr><td>1</td><td>Harvard University  &#21704;&#20315;&#22823;&#23398; </td><td>7.20%</td><td>2070 - 2350</td><td>690 - 780</td><td>690 - 790</td></tr>
 <tr><td>2</td><td>Stanford University &#26031;&#22374;&#31119;&#22823;&#23398; </td><td>8.00%</td><td>2010 - 2300</td><td>660 - 760</td><td>680 - 780</td></tr>
 <tr><td>3</td><td>Yale University &#32822;&#40065;&#22823;&#23398; </td><td>8.60%</td><td>2100 - 2370</td><td>700 - 800</td><td>700 - 780</td></tr>
 <tr><td>4</td><td>Princeton University &#26222;&#26519;&#26031;&#39039;&#22823;&#23398; </td><td>10.10%</td><td>2090 - 2360</td><td>690 - 790</td><td>700 - 790</td></tr>
 <tr><td>5</td><td>Massachusetts Institute of Technology &#40635;&#30465;&#29702;&#24037;&#23398;&#38498; </td><td>10.70%</td><td>2030 - 2320</td><td>650 - 760</td><td>720 - 800</td></tr>
 <tr><td>6</td><td>Columbia University &#21733;&#20262;&#27604;&#20122;&#22823;&#23398; </td><td>11.00%</td><td>2050 - 2320</td><td>680 - 770</td><td>680 - 780</td></tr>
 <tr><td>7</td><td>Brown University &#24067;&#26391;&#22823;&#23398; </td><td>11.20%</td><td>1990 - 2300</td><td>650 - 760</td><td>670 - 770</td></tr>
 <tr><td>8</td><td>Dartmouth College &#36798;&#29305;&#33541;&#26031;&#23398;&#38498; </td><td>13.50%</td><td>2000 - 2320</td><td>660 - 770</td><td>670 - 780</td></tr>
 <tr><td>9</td><td>California Institute of Technology &#21152;&#24030;&#29702;&#24037;&#23398;&#38498; </td><td>15.30%</td><td>2140 - 2340</td><td>690 - 770</td><td>770 - 800</td></tr>
 <tr><td>10</td><td>University of Pennsylvania &#23486;&#24030;&#22823;&#23398; </td><td>17.70%</td><td>2020 - 2290</td><td>660 - 750</td><td>690 - 780</td></tr>
 <tr><td>11</td><td>Georgetown University &#20052;&#27835;&#25958;&#22823;&#23398; </td><td>18.80%</td><td>1965 - 2235</td><td>650 - 740</td><td>660 - 750</td></tr>
 <tr><td>12</td><td>Cornell University &#24247;&#22856;&#23572;&#22823;&#23398; </td><td>19.10%</td><td>1935 - 2250</td><td>630 - 730</td><td>660 - 770</td></tr>
 <tr><td>13</td><td>Vanderbilt University &#33539;&#24503;&#22561;&#22823;&#23398; </td><td>20.10%</td><td>2010 - 2270</td><td>660 - 750</td><td>690 - 770</td></tr>
 <tr><td>14</td><td>University of California-Berkeley &#21152;&#24030;&#22823;&#23398;&#20271;&#20811;&#21033;&#26657;&#21306; </td><td>21.50%</td><td>1800 - 2170</td><td>580 - 700</td><td>620 - 760</td></tr>
 <tr><td>15</td><td>Washington University in St Louis &#21326;&#30427;&#39039;&#22823;&#23398; </td><td>22.20%</td><td>2085 - 2295</td><td>680 - 750</td><td>710 - 780</td></tr>
 <tr><td>16</td><td>Rice University &#36182;&#26031;&#22823;&#23398; </td><td>22.30%</td><td>1970 - 2270</td><td>640 - 750</td><td>680 - 780</td></tr>
 <tr><td>17</td><td>Duke University &#26460;&#20811;&#22823;&#23398; </td><td>22.40%</td><td>2000 - 2300</td><td>660 - 760</td><td>680 - 780</td></tr>
 <tr><td>18</td><td>University of California-Los Angeles &#21152;&#24030;&#22823;&#23398;&#27931;&#26441;&#30710;&#20998;&#26657; </td><td>22.80%</td><td>1730 - 2100</td><td>560 - 680</td><td>590 - 720</td></tr>
 <tr><td>19</td><td>University of Southern California &#21335;&#21152;&#24030;&#22823;&#23398; </td><td>24.40%</td><td>1910 - 2180</td><td>620 - 710</td><td>650 - 740</td></tr>
 <tr><td>20</td><td>Northwestern University &#35199;&#21271;&#22823;&#23398; </td><td>26.20%</td><td>2030 - 2280</td><td>670 - 750</td><td>690 - 780</td></tr>
 <tr><td>21</td><td>Tulane University of Louisiana </td><td>26.50%</td><td>1870 - 2110</td><td>620 - 700</td><td>620 - 700</td></tr>
 <tr><td>22</td><td>Tufts University &#22612;&#22827;&#33576;&#22823;&#23398; </td><td>26.60%</td><td>2040 - 2300</td><td>680 - 750</td><td>680 - 790</td></tr>
 <tr><td>23</td><td>Emory University &#22467;&#40664;&#37324;&#22823;&#23398; </td><td>26.60%</td><td>1960 - 2240</td><td>640 - 740</td><td>670 - 760</td></tr>
 <tr><td>24</td><td>University of Chicago &#33437;&#21152;&#21733;&#22823;&#23398; </td><td>27.30%</td><td>2055 - 2340</td><td>690 - 780</td><td>680 - 780</td></tr>
 <tr><td>25</td><td>Johns Hopkins University &#32422;&#32752;&#38669;&#26222;&#37329;&#26031;&#22823;&#23398; </td><td>27.80%</td><td>1940 - 2230</td><td>630 - 730</td><td>670 - 770</td></tr>
 <tr><td>26</td><td>University of Notre Dame &#22307;&#27597;&#22823;&#23398; </td><td>28.60%</td><td>1995 - 2265</td><td>650 - 750</td><td>680 - 760</td></tr>
 <tr><td>27</td><td>Boston College &#27874;&#26031;&#39039;&#23398;&#38498; </td><td>30.10%</td><td>1880 - 2150</td><td>610 - 700</td><td>640 - 730</td></tr>
 <tr><td>28</td><td>San Diego State University </td><td>31.20%</td><td>1395 - 1755</td><td>460 - 570</td><td>470 - 600</td></tr>
 <tr><td>29</td><td>University of Virginia-Main Campus </td><td>32.10%</td><td>1840 - 2150</td><td>600 - 710</td><td>630 - 730</td></tr>
 <tr><td>30</td><td>Brandeis University &#24067;&#20848;&#24503;&#26031;&#22823;&#23398; </td><td>32.40%</td><td>1930 - 2180</td><td>640 - 720</td><td>650 - 730</td></tr>
 <tr><td>31</td><td>Lehigh University </td><td>32.80%</td><td>1815 - 2085</td><td>580 - 670</td><td>630 - 720</td></tr>
 <tr><td>32</td><td>College of William and Mary &#23041;&#24265;&#29595;&#20029;&#23398;&#38498; </td><td>33.50%</td><td>1850 - 2160</td><td>620 - 730</td><td>620 - 720</td></tr>
 <tr><td>33</td><td>University of North Carolina at Chapel Hill&#21271;&#21345;&#32599;&#26469;&#32435;&#22823;&#23398;&#25945;&#22530;&#23665;&#20998;&#26657; </td><td>34.00%</td><td>1800 - 2080</td><td>590 - 690</td><td>620 - 700</td></tr>
 <tr><td>34</td><td>Pepperdine University </td><td>34.40%</td><td>1660 - 2010</td><td>550 - 670</td><td>560 - 680</td></tr>
 <tr><td>35</td><td>Carnegie Mellon University &#21345;&#20869;&#22522;&#26757;&#38471;&#22823;&#23398; </td><td>36.30%</td><td>1910 - 2220</td><td>620 - 720</td><td>670 - 780</td></tr>
 <tr><td>36</td><td>George Washington University </td><td>37.40%</td><td>1790 - 2070</td><td>590 - 680</td><td>600 - 690</td></tr>
 <tr><td>37</td><td>New York University &#32445;&#32422;&#22823;&#23398; </td><td>37.80%</td><td>1830 - 2140</td><td>610 - 710</td><td>600 - 720</td></tr>
 <tr><td>38</td><td>University of Rochester &#32599;&#20999;&#26031;&#29305;&#22823;&#23398; </td><td>38.70%</td><td>1820 - 2100</td><td>590 - 690</td><td>640 - 720</td></tr>
 <tr><td>39</td><td>SUNY at Binghamton </td><td>39.70%</td><td>1785 - 2025</td><td>580 - 660</td><td>610 - 690</td></tr>
 <tr><td>40</td><td>University of California-San Diego &#21152;&#21033;&#31119;&#23612;&#20122;&#22823;&#23398;&#22307;&#22320;&#20122;&#21733;&#20998;&#26657; </td><td>39.90%</td><td>1700 - 2040</td><td>540 - 660</td><td>600 - 710</td></tr>
 <tr><td>41</td><td>Stony Brook University </td><td>39.90%</td><td>1620 - 1910</td><td>520 - 620</td><td>580 - 670</td></tr>
 <tr><td>42</td><td>Georgia State University </td><td>41.00%</td><td>1450 - 1740</td><td>490 - 580</td><td>480 - 590</td></tr>
 <tr><td>43</td><td>Northeastern University </td><td>41.00%</td><td>1780 - 2040</td><td>580 - 670</td><td>620 - 700</td></tr>
 <tr><td>44</td><td>University of the Pacific </td><td>41.50%</td><td>1550 - 1960</td><td>510 - 640</td><td>540 - 680</td></tr>
 <tr><td>45</td><td>University of Maryland-College Park </td><td>41.90%</td><td>1800 - 2085</td><td>580 - 680</td><td>620 - 710</td></tr>
 <tr><td>46</td><td>Rensselaer Polytechnic Institute </td><td>42.20%</td><td>1850 - 2130</td><td>610 - 700</td><td>660 - 750</td></tr>
 <tr><td>47</td><td>University of South Florida </td><td>42.40%</td><td>1550 - 1860</td><td>520 - 620</td><td>530 - 640</td></tr>
 <tr><td>48</td><td>University of Florida </td><td>42.70%</td><td>1710 - 2040</td><td>560 - 670</td><td>580 - 690</td></tr>
 <tr><td>49</td><td>SUNY College of Environmental Science and Forestry </td><td>43.10%</td><td>1605 - 1890</td><td>530 - 620</td><td>540 - 640</td></tr>
 <tr><td>50</td><td>University of Miami </td><td>44.40%</td><td>1740 - 2050</td><td>570 - 680</td><td>600 - 700</td></tr></table>

		
	</div>
		
	</div>

app/views/static_pages/about.html.erb
<div class="container">
	
	<!-- formatting for title not currently in use
	<div class="row">
		<div class="span12">
			<p><h1></p></h1>
		</div>
	</div>
			-->
	
	<div class="row">
		<div class="span12">
			<p><h2 class="center">能力和经验</h2></p>
			<p>许多考试培训中心认为,任何人只要能讲一口流利的英语就能教SAT和TOEFL。但考过这些考试的学校的学生(和他们的考试成绩)会告诉你,这根本不是事实。在留西教育,所有的老师不仅擅长自己考试,更擅长教授中国学生如何通过考试。了解这些考试的全部,就是我们本质工作,所有的老师都要接受培训来教授给我们的学生能通过这些考试的更好的方法。</p>
			<p>此外,所有的老师都已经有通过这些考试及大学申请的经验。他们都有优异的的SAT成绩并且在美国的顶级学术机构学习过。这些经验不仅是一个附加的优势，对进行有效的考试培训也是完全有必要的。</p>
		<div class="span6"> <!-- insert picture here -->
	</div>
	
	<div class="row">
		<div class="span12">
			<p><h2 class="center">我们的目标</h2></p>
			<p>我们有一个目标。我们仅有一个非常简单的目标，就是帮助我们的学生们实现他们的梦想。我们希望能在每一个环节上帮助我们的学生能够进入美国学习。从考试准备到学校申请的每一个环节,我们都要帮助我们的学生去尽力争取他们想去的学校。</p>
		<div class="span6"> <!-- insert picture here -->
	</div>
	
	<div class="row">
		<div class="span12">
			<p><h2 class="center">信任</h2></p>
			<p>在考试培训领域，一个公司的成功仅取决于一件事:结果。我们提供大量的激励和保证,保证我们的学生通过培训得到他们需要的分数。我们还会出具学生能提高分数的定量分析报告。这些分析报告能带来更个性化的服务以及帮助学生建立更有效的培训系统。</p>
		<div class="span6"> <!-- insert picture here -->
	</div>
</div>

app/views/static_pages/contact.html.erb
<div class="container">
	<div class="row">
		<h2 class="center">Please contact us with any questions or concerns</h2>
		<h3 class="center">Telephone: 02152125489</h3>
		<h3 class="center">Email: <%=mail_to "information@qwestprep.com" %> </h3>
	</div>
</div>

app/views/static_pages/employment.html.erb
<h1>Employment Opportunities</h1>

app/views/static_pages/home.html.erb
<div class="container">
	<div id="front_center" class="hero-unit">
	</div>
	
	<div class="row">
		<div class="span12">
			<hr>
			</p><h2 class="center">美国本土专业教师团队为中国学生提供最真实、最实用的SAT、TOEFL、SSAT考前培训</h2></p>
			<hr>
			<h2 class="center">选择您的考试</h2></p
		</div>
	</div>
	  

	<div class="row">
		<div class="span4">
			<%= link_to image_tag('/logo_sat.jpg'), program_sat_path, :class => "program_button", :id => "program_button_sat" %>
			<p>
				<h3 class="center">SAT 学术能力评估考试</h3>
			</p>
        </div>
       
		<div class="span4">
			<%= link_to image_tag('/logo_toefl.jpg'), program_sat_path, :class => "program_button", :id => "program_button_toefl" %>
			<p>
				<h3 class="center">TOEFL 托福</h3>
			</p>
		</div>
		
		<div class="span4">
			<%= link_to image_tag('/logo_ssat.jpg'), program_sat_path, :class => "program_button", :id => "program_button_s_sat" %>
			<p>
				<h3 class="center">SSAT 美国中学入学考试</h3>
			</p>
        </div>
		
    </div>
</div>

app/views/static_pages/location.html.erb
<h1>StaticPages#location</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/program_consulting.html.erb
<h1>Academic Consulting</h1>

app/views/static_pages/schedule.html.erb
<h1>StaticPages#schedule</h1>
<p>Find me in app/views/static_pages/schedule.html.erb</p>